inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake}'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    
Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*
    
Layout/IndentationWidth:
  Width: 2
  
AllCops:
  Include:
    - '**/*.rb'
    
Style/Documentation:
  Enabled: false
  
Style/FrozenStringLiteralComment:
  Enabled: false